### ISSUE TITLE
scope + draft

### ISSUE THREAD

**Issue by kareniel** [vibedrive/download-manager#3]
### v1

context: soundcloud.com
event: open a link in a new tab

1. listen for tab focus
2. listen for links going out and for download
3. if download save download
4. after `n` clicks out stop

### scope

- filters out given tag names, durations, license, downloadability, liked 
- follows links going out from a given site until you start to download an archive or a music file
   then reports with all the metadata it's possible to find about the track and the artist
- unlocks download gates
- right-click on a download link -> 'get the file for this song'
- puts the file in a folder named after the hash of the content
  along with [a text file](https://github.com/jondashkyle/smarkt) containing the metadata

### todos 

- [ ] save soundlist__item tag as DOMElement

- [ ] walk it to derive metadata 
  
- [ ] save download link

- [ ]  start recording history

- [ ] on tab close, save log to leveldb
 

### document structure draft

```js
// download
{
  timestamp: 'iso',
  filename: 'nauuda - up.wav',  
  soundList__item: HTMLElement, // <li class="soundList__item">...
  song: {
    title: up
    description: `
      We've been having a lot trouble with the laptop lately, 
      and we were barely able to save this track. It's a lot 
      of fun making this kind of music, and we hope you like it.`
  },
  artist: {
    soundcloud: {
      id: 'wearenauuda',
      name: 'NAUUDA',
      description: `
        Norwegian duo

        Contact: nauuda@outlook.com

        - “◊ÜÜ∆◊`
    }
  },
  history: [
    'https://soundcloud.com/wearenauuda/up-2',
    'http://toneden.io/wearenauuda/post/up'
  ]
}
```
